language: node_js
node_js:
  - "node"
addons:
  sonarcloud: 
  
before_script:
  - npm start -- --silent &
  
script:
  # other script steps might be done before running the actual analysis
  - npm test 
  - sonar-scanner  -Dsonar.projectKey=TicTacToe -Dsonar.organization=steinko-github -Dsonar.sources=src,test -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6472ac35c070752487408fd8c946cca6b536eec2 -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report
  - cypress run --record --key a1319fd9-2c6e-4888-8f02-e62f02b5001b
 
deploy:
  provider: heroku
  api_key:
    secure: XCxgyR30CGMPqnFeVL+EYRXXtb1DeqDps88og5OPFJeWZlFp6Ck6Tlbn+XFF36YCd2DSPjtMD2OlSZYTgiqjkotColBJoc5SgymZTEiA4ce+iTjsuGUMTlV4tLSci3k4rJfIAXe1uuOxB1HUQTbXBe1GZjdgaQiQ8RTKhHKRKyvTvkgm+mE9+3A395WCCEsf1WojyvrsCY/j7s0v1nqSjjOyFGdklIEBphfIGE/2omw6yePId1FVW+tTC2JuK//9nn/hZdmdYeBBZcdJuKvlivwkcr9Ws40jxIKZrJeSsLVrcaWvBVmZP5WpFTigRLFXzOoBp1HVBZN64iM3osG/83GxOCbJXpFDa+Rtp3Xi8KgRa69+0DgRBZwTjc2i8BfLjIolhUnffHjfmbEdQEa8duxYHq/zAdKIvuBjbVc86MERZ6WB23e8efm3uW1o7mstHJNdJoB/OngUBYYpnrjL34Tn5xARRSDaPh3CXq0AgJKOd3VFSzKzTMyXnVoCZeZvLNTIQCDEjP2Ekz0cumVOc9Ig8ygB5sgJQYwSxKTBD+tCTy0JCv+PG0lFDP1joSMRWuNANawsJgP1aOQOOR8diZiYsohf6OpAUrdu17NuKdDWM2kKMWZlPNON83h12Bet2nt0BiKueAQDZkQ8Gur0Yy3ciTa6Jq+mSJDOtLiCG6Y=
  app: tictactoesko
